name: Build Extensions

on:
  push:
    branches: [ builds ]
  pull_request:
    branches: [ builds ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build extensions
        run: ./gradlew build

      - name: Upload built extensions
        uses: actions/upload-artifact@v4
        with:
          name: built-extensions
          path: "**/build/outputs/*.cs3"
